<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3i0drdt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3i0drdt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3i0drdt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3i0drdt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3i0drdt\App_KernelDevDebugContainer([
    'container.build_hash' => '3i0drdt',
    'container.build_id' => 'aa8a7fa6',
    'container.build_time' => 1583407600,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3i0drdt');
